# frontend-supply-chain-page
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-supply-chain-page-nginx-conf-pre
data:
  nginx.conf: |
    user  www-data;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format apache_format '$remote_addr - $remote_user [$time_local] "$request" '
                           '$status $body_bytes_sent "$http_referer" '
                           '"$http_user_agent"'
                           ' "$http_x_forwarded_for" $host'
                           ' "$upstream_cache_status" '
                           ' $request_time';


        access_log  /var/log/nginx/access.log  apache_format;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        include /etc/nginx/conf.d/*.conf;
    }
  frontend-supply-chain-page.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        access_log  /var/log/nginx/access.log  apache_format;
        set $prjroot /usr/share/nginx/html;
        root $prjroot/;
        index index.html;
        location ~ /version {
            root $prjroot/;
            add_header Content-Type text/plain;
        }
        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/{
            add_header Access-Control-Allow-Origin *;
            rewrite ^/api(.*)$ /$1 break;
            proxy_pass https://pos.vova.com.hk/;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-supply-chain-page-pre
  labels:
    name: frontend-supply-chain-page-pre
spec:
  selector:
    matchLabels:
      name: frontend-supply-chain-page-pre
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: frontend-supply-chain-page-pre
      labels:
        name: frontend-supply-chain-page-pre
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend-supply-chain-page-pre
          image: 832373879023.dkr.ecr.us-east-1.amazonaws.com/supply-chain:page-pre
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-port
          volumeMounts:
            - name: frontend-supply-chain-page-conf-pre
              mountPath: /etc/nginx/conf.d
            - name: nginx-conf-pre
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-log-pre
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /version
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /version
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
      volumes:
        - name: nginx-log-pre
          hostPath:
            path: /opt/data1/logs/supply-chain-pre/nginx
        - name: nginx-conf-pre
          configMap:
            name: frontend-supply-chain-page-nginx-conf-pre
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: frontend-supply-chain-page-conf-pre
          configMap:
            name: frontend-supply-chain-page-nginx-conf-pre
            items:
              - key: frontend-supply-chain-page.conf
                path: frontend-supply-chain-page.conf
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - frontend-supply-chain-page-pre
                topologyKey: kubernetes.io/hostname

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-supply-chain-page-external-elb-pre
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:832373879023:certificate/3f84bac5-ca0d-48a0-8da2-f4b9f7d1d03f
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-1980996e
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    name: frontend-supply-chain-page-pre
  ports:
    - name: svc-http
      port: 80
      targetPort: http-port
      protocol: TCP
    - name: svc-https
      port: 443
      targetPort: http-port
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 180.169.144.154/32
    - 140.206.96.158/32
